from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_guiMakeGraphWindow(object):
    def setupUi(self, guiMakeGraphWindow):
        guiMakeGraphWindow.setObjectName("guiMakeGraphWindow")
        guiMakeGraphWindow.resize(680, 680)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            guiMakeGraphWindow.sizePolicy().hasHeightForWidth()
        )
        guiMakeGraphWindow.setSizePolicy(sizePolicy)
        guiMakeGraphWindow.setMaximumSize(QtCore.QSize(680, 680))
        self.label = QtWidgets.QLabel(guiMakeGraphWindow)
        self.label.setGeometry(QtCore.QRect(20, 20, 640, 480))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../Python311/9round-logo-9.jpg"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.startSlider = QtWidgets.QSlider(guiMakeGraphWindow)
        self.startSlider.setGeometry(QtCore.QRect(60, 50, 21, 421))
        self.startSlider.setMaximum(100)
        self.startSlider.setProperty("value", 0)
        self.startSlider.setSliderPosition(0)
        self.startSlider.setOrientation(QtCore.Qt.Vertical)
        self.startSlider.setInvertedAppearance(False)
        self.startSlider.setInvertedControls(False)
        self.startSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.startSlider.setTickInterval(10)
        self.startSlider.setObjectName("startSlider")
        self.yellowSlider = QtWidgets.QSlider(guiMakeGraphWindow)
        self.yellowSlider.setGeometry(QtCore.QRect(450, 50, 21, 421))
        self.yellowSlider.setMaximum(100)
        self.yellowSlider.setProperty("value", 0)
        self.yellowSlider.setSliderPosition(0)
        self.yellowSlider.setOrientation(QtCore.Qt.Vertical)
        self.yellowSlider.setInvertedAppearance(False)
        self.yellowSlider.setInvertedControls(False)
        self.yellowSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.yellowSlider.setTickInterval(10)
        self.yellowSlider.setObjectName("yellowSlider")
        self.redSlider = QtWidgets.QSlider(guiMakeGraphWindow)
        self.redSlider.setGeometry(QtCore.QRect(550, 50, 21, 421))
        self.redSlider.setStyleSheet("")
        self.redSlider.setMaximum(100)
        self.redSlider.setProperty("value", 0)
        self.redSlider.setSliderPosition(0)
        self.redSlider.setOrientation(QtCore.Qt.Vertical)
        self.redSlider.setInvertedAppearance(False)
        self.redSlider.setInvertedControls(False)
        self.redSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.redSlider.setTickInterval(10)
        self.redSlider.setObjectName("redSlider")
        self.saveApplyButton = QtWidgets.QPushButton(guiMakeGraphWindow)
        self.saveApplyButton.setGeometry(QtCore.QRect(510, 640, 75, 23))
        self.saveApplyButton.setObjectName("saveApplyButton")
        self.cancelButton = QtWidgets.QPushButton(guiMakeGraphWindow)
        self.cancelButton.setGeometry(QtCore.QRect(590, 640, 75, 23))
        self.cancelButton.setObjectName("cancelButton")
        self.greenInterpTypeSelect = QtWidgets.QSpinBox(guiMakeGraphWindow)
        self.greenInterpTypeSelect.setGeometry(QtCore.QRect(150, 500, 171, 21))
        self.greenInterpTypeSelect.setSpecialValueText("")
        self.greenInterpTypeSelect.setMaximum(13)
        self.greenInterpTypeSelect.setProperty("value", 0)
        self.greenInterpTypeSelect.setObjectName("greenInterpTypeSelect")
        self.yellowInterpTypeSelect_2 = QtWidgets.QSpinBox(guiMakeGraphWindow)
        self.yellowInterpTypeSelect_2.setGeometry(QtCore.QRect(480, 500, 61, 21))
        self.yellowInterpTypeSelect_2.setSpecialValueText("")
        self.yellowInterpTypeSelect_2.setMaximum(13)
        self.yellowInterpTypeSelect_2.setProperty("value", 0)
        self.yellowInterpTypeSelect_2.setObjectName("yellowInterpTypeSelect_2")
        self.redInterpTypeSelect = QtWidgets.QSpinBox(guiMakeGraphWindow)
        self.redInterpTypeSelect.setGeometry(QtCore.QRect(570, 500, 61, 21))
        self.redInterpTypeSelect.setSpecialValueText("")
        self.redInterpTypeSelect.setMaximum(13)
        self.redInterpTypeSelect.setProperty("value", 0)
        self.redInterpTypeSelect.setObjectName("redInterpTypeSelect")
        self.directions = QtWidgets.QLabel(guiMakeGraphWindow)
        self.directions.setGeometry(QtCore.QRect(20, 560, 251, 81))
        self.directions.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop
        )
        self.directions.setWordWrap(True)
        self.directions.setObjectName("directions")
        self.sliderValueBoxStart = QtWidgets.QLineEdit(guiMakeGraphWindow)
        self.sliderValueBoxStart.setGeometry(QtCore.QRect(50, 480, 41, 20))
        self.sliderValueBoxStart.setText("")
        self.sliderValueBoxStart.setObjectName("sliderValueBoxStart")
        self.sliderValueBoxYellow = QtWidgets.QLineEdit(guiMakeGraphWindow)
        self.sliderValueBoxYellow.setGeometry(QtCore.QRect(440, 480, 41, 20))
        self.sliderValueBoxYellow.setText("")
        self.sliderValueBoxYellow.setObjectName("sliderValueBoxYellow")
        self.sliderValueBoxRed = QtWidgets.QLineEdit(guiMakeGraphWindow)
        self.sliderValueBoxRed.setGeometry(QtCore.QRect(540, 480, 41, 20))
        self.sliderValueBoxRed.setText("")
        self.sliderValueBoxRed.setObjectName("sliderValueBoxRed")
        self.endSlider = QtWidgets.QSlider(guiMakeGraphWindow)
        self.endSlider.setGeometry(QtCore.QRect(620, 50, 21, 421))
        self.endSlider.setStyleSheet("")
        self.endSlider.setMaximum(100)
        self.endSlider.setProperty("value", 0)
        self.endSlider.setSliderPosition(0)
        self.endSlider.setOrientation(QtCore.Qt.Vertical)
        self.endSlider.setInvertedAppearance(False)
        self.endSlider.setInvertedControls(False)
        self.endSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.endSlider.setTickInterval(10)
        self.endSlider.setObjectName("endSlider")
        self.sliderValueBoxEnd = QtWidgets.QLineEdit(guiMakeGraphWindow)
        self.sliderValueBoxEnd.setGeometry(QtCore.QRect(610, 480, 41, 20))
        self.sliderValueBoxEnd.setText("")
        self.sliderValueBoxEnd.setObjectName("sliderValueBoxEnd")

        self.retranslateUi(guiMakeGraphWindow)
        QtCore.QMetaObject.connectSlotsByName(guiMakeGraphWindow)

    def retranslateUi(self, guiMakeGraphWindow):
        _translate = QtCore.QCoreApplication.translate
        guiMakeGraphWindow.setWindowTitle(
            _translate("guiMakeGraphWindow", "Graph Editor")
        )
        self.saveApplyButton.setText(_translate("guiMakeGraphWindow", "Save/Apply"))
        self.cancelButton.setText(_translate("guiMakeGraphWindow", "Cancel"))
        self.directions.setText(
            _translate(
                "guiMakeGraphWindow",
                "Edit this graph blah blah blah, pick the number to change the interpolation type as;lkadsfljfdalkjfda",
            )
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    guiMakeGraphWindow = QtWidgets.QDialog()
    ui = Ui_guiMakeGraphWindow()
    ui.setupUi(guiMakeGraphWindow)
    guiMakeGraphWindow.show()
    sys.exit(app.exec_())
